skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm_contract = "9XKn4NPug93QgEPneXbx778297K4jBYxJkvWTt5Eq9pt"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
